import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css"; // Ensure global styles are correctly imported
import Layout from "../components/layout/Layout"; // Import Layout component


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout> {/* Wrapping all pages inside Layout */}
          {children} {/* This must be here to render page.js */}
        </Layout>
      </body>
    </html>
  );
}
